# Упражнения с NumPy 

Давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы несколько более сложных вопросов.

Важно! Код, который вы напишите в этом ноутбуке, вам нужно сохранить в виде файла c именем "Numpy_solutions.ipynb" в вашем личном репозитории на GitHub.

#### 1. Импорт NumPy 

In [1]:
import numpy as np

#### 2. Создать массив из 10 нулей

In [18]:
# Ваш кодa
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# не пишите код в этой ячейке

#### 3. Создать массив из 10 единиц

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# не пишите код в этой ячейке

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создать массив из  10 пятерок

In [21]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# не пишите код в этой ячейке

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создать массив из целых чисел от 10 до 50

In [26]:
a=np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# не пишите код в этой ячейке

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создать массив из четных числел от 10 до 50

In [27]:
a=np.arange(10,51,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# не пишите код в этой ячейке

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создать матрицу 3х3 с числами от 0 до 8

In [42]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# не пишите код в этой ячейке

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создать единичную матрицу 3x3 

In [44]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# не пишите код в этой ячейке

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Используйте NumPy для генерации случайного числа от 0 до 1
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [47]:
np.random.rand()

0.5065789697032663

In [9]:
# не пишите код в этой ячейке

array([0.65248055])

#### Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [61]:
np.random.normal(1,15,25)

array([-23.57324645, -12.83327083, -16.73843123, -18.14961522,
        27.42640332, -13.00334649,  23.51008203,  21.20087497,
         9.98731618,  27.95778752,   5.25303818,   6.13108898,
         0.40506161,  15.08387139,  23.36196298, -13.27464308,
        27.33165666,   4.70860101,   5.33310233,   1.96250127,
         6.32413593,   0.87904399, -13.15614476,  -0.23484006,
        18.25158236])

In [10]:
# не пишите код в этой ячейке

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Создайте следующую матрицу:

In [77]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [70]:
# не пишите код в этой ячейке

#### 12. Создайте массив из 20 линейно расположенных точек между 0 и 1:

In [78]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# не пишите код в этой ячейке

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy индексация и выборка

Дана стартовая матрица (обязательно запустите ячейку ниже!). Вам необходимо повторить выходные результаты матрицы:

In [79]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который воспроизводит вывод, показанный ниже.


In [153]:
# CODE HERE
mat[1:][1:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# не пишите код в этой ячейке

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который воспроизводит вывод, показанный ниже.

In [158]:
mat[3][4]

20

In [15]:
# не пишите код в этой ячейке

20

#### 15. Напишите код, который воспроизводит вывод, показанный ниже.

In [185]:
mat[:,1][:3]

array([ 2,  7, 12])

In [16]:
# не пишите код в этой ячейке

array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который воспроизводит вывод, показанный ниже.

In [186]:
mat[4]

array([21, 22, 23, 24, 25])

In [17]:
# не пишите код в этой ячейке

array([21, 22, 23, 24, 25])

#### 17. Напишите код, который воспроизводит вывод, показанный ниже.

In [218]:
mat[3:][0:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# не пишите код в этой ячейке

## Операции NumPy 

#### 18. Получить сумму всех значений в матрице mat

In [220]:
mat.sum()

325

In [19]:
# не пишите код в этой ячейке

325

#### 19. Получить стандартное отклонение в матрице mat

In [221]:
mat.std()

7.211102550927978

In [20]:
# не пишите код в этой ячейке

7.211102550927978

#### 20. Получить сумму значений в колонках в матрице mat

In [224]:
mat.sum(0)

array([55, 60, 65, 70, 75])

In [21]:
# не пишите код в этой ячейке

array([55, 60, 65, 70, 75])

## Бонусный вопрос

Есть ли способ гарантировать, что мы всегда получим одинаковые случайные числа?

In [ ]:
да, способ seed